import test from 'node:test';
import assert from 'node:assert/strict';
import { defaults, normalizeStats, validateSettings } from '../state.js';

test('daily stats reset using local date, preserving current day', () => {
  const date = new Date(2026, 8, 11, 0, 1);
  assert.deepEqual(normalizeStats({day:'2026-9-10',water:7,stretch:2},date), {day:'2026-9-11',water:0,stretch:0});
  assert.equal(normalizeStats({day:'2026-9-11',water:3,stretch:1},date).water,3);
});
test('settings reject invalid values and ignore unrelated fields', () => {
  for (const goal of [0,21,NaN,2.5]) assert.throws(() => validateSettings({goal}));
  assert.throws(() => validateSettings({waterMinutes:0}));
  assert.deepEqual(validateSettings({goal:10,pausedUntil:123}),{goal:10});
});
test('background schedules, records, pauses, snoozes and restores alarms', async t => {
  t.mock.timers.enable({apis:['Date'],now:new Date(2026,8,28,9,0).getTime()});
  const listeners = {};
  const event = name => ({addListener(fn) {listeners[name] = fn;}});
  const alarms = new Map();
  const notifications = new Map();
  const latestId = kind => [...notifications.keys()].find(id => id === kind || id.startsWith(`mam:${kind}:`));
  const hasNotification = kind => Boolean(latestId(kind));
  let data = {};
  globalThis.chrome = {
    runtime: {id:'test',onInstalled:event('install'),onStartup:event('startup'),onMessage:event('message')},
    storage:{local:{async get(){return structuredClone(data);},async set(value){data = {...data,...structuredClone(value)};}}},
    alarms:{onAlarm:event('alarm'),async create(name,options){alarms.set(name,{name,...options,scheduledTime:options.when || Date.now()+options.delayInMinutes*60000});},async clear(name){return alarms.delete(name);},async get(name){return alarms.get(name);},async getAll(){return [...alarms.values()];}},
    notifications:{onButtonClicked:event('button'),async getAll(){return Object.fromEntries(notifications);},async create(id,options){notifications.set(id,options);},async clear(id){return notifications.delete(id);}}
  };
  await import('../background.js');
  await listeners.install();
  assert.equal(alarms.get('water').scheduledTime,Date.now()+30*60000);
  assert.equal(alarms.get('stretch').scheduledTime,Date.now()+60*60000);
  const send = message => new Promise(resolve => listeners.message(message,{id:'test'},resolve));
  const initialTime = alarms.get('water').scheduledTime;
  await send({type:'get'});
  assert.equal(alarms.get('water').scheduledTime,initialTime);
  await Promise.all(Array.from({length:5},() => send({type:'complete',kind:'water'})));
  assert.equal(data.stats.water,5);
  await listeners.alarm({name:'water'});
  assert.equal(notifications.get(latestId('water')).buttons.length,2);
  const firstId = latestId('water');
  await listeners.alarm({name:'water'});
  const secondId = latestId('water');
  assert.notEqual(firstId,secondId,'unread reminder is replaced by a fresh notification ID');
  assert.equal(notifications.size,1,'old unread notification is cleared');
  await listeners.button(firstId,0);
  assert.equal(data.stats.water,5,'stale button event cannot record a completion');
  await listeners.button(secondId,1);
  assert.ok(alarms.has('snooze-water'));
  await listeners.alarm({name:'snooze-water'});
  const snoozeId = latestId('water');
  assert.notEqual(snoozeId,secondId);
  await listeners.button(snoozeId,0);
  assert.equal(data.stats.water,6,'fresh ID routes completion to water');
  await send({type:'complete',kind:'water'});
  assert.ok(!alarms.has('snooze-water'));
  await send({type:'pause'});
  assert.ok(!alarms.has('water'));
  assert.ok(alarms.has('resume'));
  notifications.clear();
  await listeners.alarm({name:'stretch'});
  assert.equal(notifications.size,0);
  await send({type:'pause',resume:true});
  assert.ok(alarms.has('water'));
  await send({type:'save',settings:{waterEnabled:false,stretchMinutes:15}});
  assert.ok(!alarms.has('water'));
  assert.equal(alarms.get('stretch').scheduledTime,Date.now()+15*60000);
  alarms.clear();
  await listeners.startup();
  assert.ok(alarms.has('stretch'));
  assert.ok(!alarms.has('water'));
  const invalid = await send({type:'save',settings:{goal:-1}});
  assert.equal(invalid.ok,false);
  assert.equal(data.settings.goal,defaults.goal);
  let focused = true, injectable = true, shown = true;
  const delivered = [];
  chrome.windows = { async getLastFocused() { return { id: 1, focused }; } };
  chrome.tabs = {
    async query() { return [{ id: 42 }]; },
    async sendMessage(id, message) { delivered.push({id,...message}); return {shown}; }
  };
  chrome.scripting = { async executeScript() { if (!injectable) throw new Error('Restricted page'); } };
  assert.equal((await send({type:'get'})).settings.inPageEnabled,false);
  await listeners.alarm({name:'stretch'});
  await send({type:'test'});
  assert.equal(delivered.length,0,'default setting never delivers in-page reminders');
  assert.ok(hasNotification('stretch'));
  assert.ok(hasNotification('test'));
  await send({type:'save',settings:{inPageEnabled:true}});
  assert.equal(data.settings.inPageEnabled,true);
  notifications.clear();
  await listeners.alarm({name:'stretch'});
  assert.equal(delivered.at(-1).kind,'stretch');
  assert.equal(notifications.size,0,'in-page delivery avoids duplicate desktop notification');
  const countBeforeTest = data.stats.water;
  await send({type:'test'});
  assert.equal(delivered.at(-1).test,true);
  assert.equal(data.stats.water,countBeforeTest,'preview does not record a drink');
  await send({type:'snooze',kind:'stretch'});
  assert.equal(alarms.get('snooze-stretch').scheduledTime,Date.now()+5*60000);
  await send({type:'complete',kind:'stretch'});
  assert.ok(!alarms.has('snooze-stretch'));
  injectable = false;
  await listeners.alarm({name:'stretch'});
  assert.ok(hasNotification('stretch'),'restricted pages use desktop notification');
  injectable = true; focused = false; notifications.clear();
  await listeners.alarm({name:'stretch'});
  assert.ok(hasNotification('stretch'),'unfocused browser uses desktop notification');
  focused = true; shown = false; notifications.clear();
  await listeners.alarm({name:'stretch'});
  assert.ok(hasNotification('stretch'),'tab hidden during delivery uses desktop notification');
  await send({type:'save',settings:{inPageEnabled:false}});
  const deliveryCount = delivered.length;
  shown = true;
  notifications.clear();
  await listeners.alarm({name:'stretch'});
  await send({type:'test'});
  assert.equal(delivered.length,deliveryCount,'turning off stops both scheduled and test in-page notifications');
  assert.ok(hasNotification('stretch'));
  assert.ok(hasNotification('test'));
  assert.equal((await send({type:'get'})).settings.inPageEnabled,false,'choice persists');
  // Quantities are immutable after logging, even if the user's cup changes.
  await send({type:'save',settings:{cupMl:350}});
  const beforeMl=data.stats.waterMl;
  await send({type:'complete',kind:'water'});
  assert.equal(data.stats.waterMl,beforeMl+350);
  const undoId=data.lastAction.id;
  await send({type:'save',settings:{cupMl:500}});
  assert.equal(data.stats.waterMl,beforeMl+350);
  await send({type:'undo',id:undoId});
  assert.equal(data.stats.waterMl,beforeMl);
  assert.equal((await send({type:'undo',id:undoId})).ok,false);
  await send({type:'save',settings:{waterEnabled:true,sound:false}});
  await listeners.alarm({name:'water'});
  const waterId=latestId('water');
  assert.equal(notifications.get(waterId).silent,true);
  assert.equal(notifications.get(waterId).buttons[0].title,'Đã uống 500 ml');
  await send({type:'save',settings:{cupMl:250}});
  await listeners.button(waterId,0);
  assert.equal(data.stats.waterMl,beforeMl+500,'notification preserves the amount shown on its button');
  await send({type:'save',settings:{scheduleEnabled:true}});
  t.mock.timers.setTime(new Date(2026,8,28,12,15).getTime());
  notifications.clear();
  await listeners.alarm({name:'water'});
  assert.equal(notifications.size,0,'no reminders during lunch');
  assert.equal(alarms.get('water').scheduledTime,new Date(2026,8,28,13,0).getTime());
  await send({type:'snooze',kind:'water'});
  assert.equal(alarms.get('snooze-water').scheduledTime,new Date(2026,8,28,13,0).getTime());
  await send({type:'pause',minutes:25});
  const focusEnd=Date.now()+25*60000;
  assert.equal(alarms.get('resume').scheduledTime,focusEnd);
  assert.ok(!alarms.has('snooze-water'));
  assert.ok(!alarms.has('water'));
  await listeners.startup();
  assert.ok(!alarms.has('water'),'focus survives browser restart');
  t.mock.timers.setTime(focusEnd);
  await listeners.alarm({name:'resume'});
  assert.ok(alarms.has('water'),'automatically resumes after focus');
  const oldDay=data.stats.day, oldWater=data.stats.waterMl, lastId=data.lastAction.id;
  t.mock.timers.setTime(new Date(2026,8,29,9,0).getTime());
  const nextDay=await send({type:'get'});
  assert.equal(nextDay.stats.waterMl,0);
  assert.equal(nextDay.history[oldDay].waterMl,oldWater,'archives totals across midnight');
  await send({type:'undo',id:lastId});
  assert.equal(data.history[oldDay].waterMl,oldWater-500,'undo adjusts the original day');
  assert.equal(data.stats.waterMl,0);
  // A late alarm after sleep must not notify outside the selected weekdays.
  t.mock.timers.setTime(new Date(2026,9,3,10,0).getTime());
  notifications.clear();
  await listeners.alarm({name:'stretch'});
  assert.equal(notifications.size,0);
  assert.equal(new Date(alarms.get('stretch').scheduledTime).getDay(),1);
});
